### ISSUE TITLE
Test failure on branch 4.10.x commit 63ba399c: CfdpIntegrationTest.testClass2WithPacketLoss

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs#397]
One of the tests if failing on the HEAD of the 4.10.x branch (commit 63ba399c) on Ubuntu 18.04 with Oracle Java 11.0.7.

To build, I just did a simple git clone, git checkout 4.10.x and mvn clean install. 

```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.673 s - in org.yamcs.tctm.CcsdsPacketTest
[INFO] Running org.yamcs.tctm.TmFileReaderTest
May 14 13:07:55.496 _global [1] org.yamcs.api.Slf4jEventProducer [WARNING] [IssPacketPreprocessor][SEQ_COUNT_JUMP] Sequence count jump for apid: 997 old seq: 0 newseq: 6560
May 14 13:07:55.547 _global [1] org.yamcs.api.Slf4jEventProducer [WARNING] [IssPacketPreprocessor][SEQ_COUNT_JUMP] Sequence count jump for apid: 991 old seq: 0 newseq: 13388
May 14 13:07:55.676 _global [1] org.yamcs.api.Slf4jEventProducer [WARNING] [IssPacketPreprocessor][SEQ_COUNT_JUMP] Sequence count jump for apid: 997 old seq: 0 newseq: 6560
May 14 13:07:55.677 _global [1] org.yamcs.api.Slf4jEventProducer [WARNING] [IssPacketPreprocessor][SEQ_COUNT_JUMP] Sequence count jump for apid: 991 old seq: 0 newseq: 13388
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.12 s - in org.yamcs.tctm.TmFileReaderTest
[INFO] Running org.yamcs.cfdp.CfdpIntegrationTest
[ERROR] Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 47.989 s <<< FAILURE! - in org.yamcs.cfdp.CfdpIntegrationTest
[ERROR] testClass2WithPacketLoss(org.yamcs.cfdp.CfdpIntegrationTest)  Time elapsed: 9.523 s  <<< FAILURE!
java.lang.AssertionError: expected:<COMPLETED> but was:<FAILED>
	at org.yamcs.cfdp.CfdpIntegrationTest.uploadAndCheck(CfdpIntegrationTest.java:160)
	at org.yamcs.cfdp.CfdpIntegrationTest.testClass2WithPacketLoss(CfdpIntegrationTest.java:116)

[INFO] Running org.yamcs.LongWebsocketFrameTest


[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   CfdpIntegrationTest.testClass2WithPacketLoss:116->uploadAndCheck:160 expected:<COMPLETED> but was:<FAILED>
[INFO] 
[ERROR] Tests run: 560, Failures: 1, Errors: 0, Skipped: 16
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Yamcs 4.10.10-SNAPSHOT:
[INFO] 
[INFO] Yamcs .............................................. SUCCESS [ 14.856 s]
[INFO] Yamcs :: API ....................................... SUCCESS [11:19 min]
[INFO] Yamcs :: Yamcs Client .............................. SUCCESS [ 22.084 s]
[INFO] Yamcs :: XTCE ...................................... SUCCESS [ 42.185 s]
[INFO] Yamcs :: Core ...................................... FAILURE [  01:00 h]
[INFO] Yamcs :: Packet Viewer ............................. SKIPPED
[INFO] Yamcs :: Artemis ................................... SKIPPED
[INFO] Yamcs :: TSE ....................................... SKIPPED
[INFO] Yamcs :: Web Interface ............................. SKIPPED
[INFO] Yamcs :: Distribution .............................. SKIPPED
[INFO] Yamcs :: Example Simulation ........................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:13 h
[INFO] Finished at: 2020-05-14T13:26:53+02:00
[INFO] ------------------------------------------------------------------------

```

**Comment by fqqb** [comment]
This test is working OK on master (see GitHub "Actions" tab). It looks like your build box is very slow (1h on core). My guess is that this causes you to hit a timeout either in the test code, or on the server. Closing because I don't think there's much we can do here.
