### ISSUE TITLE
Packet viewer will not start on Linux if preferences are not present

### ISSUE THREAD

**Issue by merose** [yamcs/yamcs#689]
I have deleted all Java preferences, to make sure startup is clean. I get this error.

~~~
$ bin/packet-viewer.sh
No columns definition found in ui preferences
Exception in thread "main" java.lang.NullPointerException
	at org.yamcs.ui.packetviewer.PacketViewer.getRecentFiles(PacketViewer.java:1076)
	at org.yamcs.ui.packetviewer.PacketViewer.updateMenuWithRecentFiles(PacketViewer.java:495)
	at org.yamcs.ui.packetviewer.PacketViewer.installMenubar(PacketViewer.java:406)
	at org.yamcs.ui.packetviewer.PacketViewer.<init>(PacketViewer.java:272)
	at org.yamcs.ui.packetviewer.PacketViewer.main(PacketViewer.java:1239)
~~~

Looking at the source, it looks like the packet viewer expects preference to be present in advance.

Also, processing of a URL argument is wrong:

~~~
$ bin/packet-viewer.sh http://localhost:8090/yamcs
-x argument must be specified when opening a file
usage: packetviewer.sh [-h] [-l n] [-x name] [-s name] [file|url]
$ 
~~~

Looking at the source, it looks like a "file" argument is assumed to be a file.

~~~
        if (file != null && file.startsWith("http://")) {
            if (!options.containsKey("-l")) {
                maxLines = 1000; // Default for realtime connections
            }
        }
        if (file != null) {
            if (!options.containsKey("-x")) {
                printArgsError("-x argument must be specified when opening a file");
            }
        }
~~~

It looks like the second "if" should be an "else if".

**Comment by fqqb** [comment]
Both issues have been fixed on master.

Note that when providing a Server URL, you must also specify the target instance using `-i instance`.
